-- MySQL Script generated by MySQL Workbench
-- 04/14/15 00:23:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blackchat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blackchat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blackchat` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `blackchat` ;

-- -----------------------------------------------------
-- Table `blackchat`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blackchat`.`users` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `login` LONGTEXT NOT NULL,
  `psw` LONGTEXT NOT NULL,
  UNIQUE INDEX `login_UNIQUE` (`userID` ASC),
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blackchat`.`dialogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blackchat`.`dialogs` (
  `dialogID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`dialogID`),
  UNIQUE INDEX `dialogID_UNIQUE` (`dialogID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blackchat`.`users_dialogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blackchat`.`users_dialogs` (
  `userID` INT NOT NULL,
  `dialogID` INT NOT NULL,
  PRIMARY KEY (`userID`, `dialogID`),
  INDEX `dialog_idx` (`dialogID` ASC),
  CONSTRAINT `user`
    FOREIGN KEY (`userID`)
    REFERENCES `blackchat`.`users` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `dialog`
    FOREIGN KEY (`dialogID`)
    REFERENCES `blackchat`.`dialogs` (`dialogID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blackchat`.`mails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blackchat`.`mails` (
  `dialogID` INT NOT NULL,
  `mailID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `text` LONGTEXT NOT NULL,
  PRIMARY KEY (`dialogID`, `mailID`),
  INDEX `userID_idx` (`userID` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
